import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        {/* Fixed background grid - works on all mobile browsers */}
        <div
          style={{
            position: "fixed",
            inset: 0,
            width: "100vw",
            height: "100vh",
            zIndex: -1,
            backgroundColor: "#ffffff",
            backgroundImage:
              "linear-gradient(rgba(30,30,30,0.18) 1.5px, transparent 1.5px), linear-gradient(90deg, rgba(30,30,30,0.18) 1.5px, transparent 1.5px)",
            backgroundSize: "40px 40px",
          }}
        />
        {children}
      </body>
    </html>
  );
}
